spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
